import { xchacha20poly1305 } from "@noble/ciphers/chacha.js";

import { fromBase58 } from "@shared/base58";
import { parseShareTool, type ShareTool } from "@shared/tool";
import type { ConnectionFile } from "./types";

export function decryptBlob(blob: string, pairingCode: string): ConnectionFile {
  // Pairing code is the full 32-byte session key encoded in base58
  const codeBytes = fromBase58(pairingCode);
  if (codeBytes.length < 32) throw new Error("Pairing code too short");
  const key = codeBytes.slice(0, 32);

  const nonceHex = blob.slice(0, 48);
  const ctHex = blob.slice(48);
  const nonce = Uint8Array.from(Buffer.from(nonceHex, "hex"));
  const ciphertext = Uint8Array.from(Buffer.from(ctHex, "hex"));

  const cipher = xchacha20poly1305(key, nonce);
  const plaintext = cipher.decrypt(ciphertext);
  return JSON.parse(new TextDecoder().decode(plaintext)) as ConnectionFile;
}

export interface ParsedConnectUrl {
  serverUrl: string;
  pairingCode: string;
  /** Tool hint from `?tool=codex`. The encrypted pairing blob is authoritative. */
  tool: ShareTool | null;
}

// Format: codeshare://host:port/connect/<pairingCode>[?tool=codex]
// (claudeshare:// and https:// accepted for links generated by older versions)
// The server does not need to handle this path — it's parsed client-side only.
export function parseConnectUrl(url: string): ParsedConnectUrl | null {
  if (!/^(codeshare|claudeshare|https):\/\//.test(url)) return null;
  const normalised = url.replace(/^(codeshare|claudeshare):\/\//, "https://");
  const match = normalised.match(/^(https:\/\/.+?)\/connect\/([A-Za-z0-9]+)(?:\?([^#]*))?$/);
  if (!match) return null;
  const query = new URLSearchParams(match[3] ?? "");
  return { serverUrl: match[1], pairingCode: match[2], tool: parseShareTool(query.get("tool")) };
}

/** True when the pairing code decodes to a full 32-byte session key. */
export function isCompletePairingCode(code: string): boolean {
  try {
    return fromBase58(code).length >= 32;
  } catch {
    return false;
  }
}

/**
 * Finds a connect link inside arbitrary pasted text. Links copied from the
 * sharer's terminal are often wrapped onto several lines or surrounded by
 * other text, so all whitespace is removed and the link is searched for
 * anywhere in the input. Returns the parsed link plus whether the pairing
 * code is complete (a wrapped copy is frequently cut mid-code).
 */
export function extractConnectUrl(
  text: string,
): { parsed: ParsedConnectUrl; complete: boolean } | null {
  const compact = text.replace(/\s+/g, "").replace(/[.,;)\]'"`]+$/, "");
  const start = compact.search(/(codeshare|claudeshare|https):\/\//);
  if (start === -1) return null;
  const candidate = compact.slice(start);
  const parsed = parseConnectUrl(candidate);
  if (!parsed) return null;
  return { parsed, complete: isCompletePairingCode(parsed.pairingCode) };
}

/** Does the text look like the beginning of a connect link (scheme present)? */
export function looksLikeConnectUrl(text: string): boolean {
  return /(codeshare|claudeshare|https):\/\//.test(text.replace(/\s+/g, ""));
}
